backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "content"
    label: "ページ"
    format: "json"
    folder: "assets/content/blog"
    create: true
    slug: "{{fields.slug}}"
    editor:
      preview: false
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "URL(英数字を使ってください)", name: "slug", widget: "string" }
      - { label: "かんたんな説明文", name: "description", widget: "string" }
      - { label: "作成日", name: "date", widget: "datetime" }
      - {
          label: "カバー画像",
          name: "image",
          widget: "image",
          required: false,
          tagname: "",
        }
      - { label: "本文 (日本語)", name: "body", widget: "markdown" }

      - { label: "タイトル (英語)", name: "title_en", widget: "string" }
      - {
          label: "かんたんな説明文 (英語)",
          name: "description_en",
          widget: "string",
        }
      - { label: "本文 (英語)", name: "body_en", widget: "markdown" }

  - name: "news"
    label: "ニュース"
    format: "json"
    folder: "assets/content/news"
    create: true
    slug: "{{fields.slug}}"
    editor:
      preview: false
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "URL(英数字を使ってください)", name: "slug", widget: "string" }
      - { label: "かんたんな説明文", name: "description", widget: "string" }
      - { label: "作成日", name: "date", widget: "datetime" }
      - {
          label: "カバー画像",
          name: "image",
          widget: "image",
          required: false,
          tagname: "",
        }
      - { label: "本文 (日本語)", name: "body", widget: "markdown" }
